name: Build and Push Docker Image

on:
  push:
    branches:
      - master # Change this to your desired branch
env:
  APP: frontend-vue
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker image
        run: |
              TAG=` echo ${{github.sha}} | cut -c1-6`
              echo "$TAG"
              docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/${{env.APP}}:$TAG -t ${{ secrets.DOCKER_HUB_USERNAME}}/${{env.APP}}:latest .
              docker push ${{secrets.DOCKER_HUB_USERNAME}}/${{env.APP}}:$TAG
              docker push ${{secrets.DOCKER_HUB_USERNAME}}/${{env.APP}}:latest
